USE [master]
GO

/****** Object:  Database [SistemaSolar]    Script Date: 12/08/2021 6:11:45 p. m. ******/
CREATE DATABASE [SistemaSolar]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SistemaSolar', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SistemaSolar.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SistemaSolar_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SistemaSolar_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SistemaSolar].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SistemaSolar] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SistemaSolar] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SistemaSolar] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SistemaSolar] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SistemaSolar] SET ARITHABORT OFF 
GO

ALTER DATABASE [SistemaSolar] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SistemaSolar] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SistemaSolar] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SistemaSolar] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SistemaSolar] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SistemaSolar] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SistemaSolar] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SistemaSolar] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SistemaSolar] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SistemaSolar] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SistemaSolar] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SistemaSolar] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SistemaSolar] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SistemaSolar] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SistemaSolar] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SistemaSolar] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SistemaSolar] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SistemaSolar] SET RECOVERY FULL 
GO

ALTER DATABASE [SistemaSolar] SET  MULTI_USER 
GO

ALTER DATABASE [SistemaSolar] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SistemaSolar] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SistemaSolar] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SistemaSolar] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SistemaSolar] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SistemaSolar] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SistemaSolar] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SistemaSolar] SET  READ_WRITE 
GO


